version: "3.3"
services:
  test:
    build: minecraft
    env_file: default.env
    volumes:
      - worlds-test:/worlds
    ports:
      - 25565:25565
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
  sync:
    build: sync
    privileged: True
    volumes: 
      - aws:/root/.aws
      - cloud:/cloud
      - worlds-test:/worlds/test
#  waterfall:
#    build: waterfall
volumes:
  worlds-test:
  aws:
  cloud: