version: "3.3"
services:
  # sync:
  #   build: sync
  #   privileged: True
  #   volumes: 
  #     - aws:/root/.aws
  #     - cloud:/cloud
  #     - worlds-test:/worlds/test
  #     - worlds-survival:/worlds/survival
  #     - worlds-build:/worlds/build
  db:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
  test:
    restart: always
    build: minecraft
    env_file: default.env
    depends_on:
      - db
    environment: 
      - UWU=test
    volumes:
      - ./cloud:/cloud
    ports:
      - 25565:25565

#  waterfall:
#    build: waterfall
volumes:
  worlds-test:
  worlds-survival:
  worlds-build:
  aws:
  cloud: