version: "3.3"
services:
  test:
    build: minecraft
    env_file: default.env
    volumes:
      - ./base:/base:cached,ro
      - ./diff:/diff:delegated
    privileged: True
    ports:
      - 25565:25565
  sql:
    image: mysql
  sync:
    build: sync
    volumes: 
      - aws:/root/.aws
#  waterfall:
#    build: waterfall
