version: "3.3"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
    ports:
    - 3306
  build:
    restart: always
    privileged: True
    build: minecraft
    tmpfs:
      - /tmp
    env_file: default.env
    depends_on:
      - db
    environment: 
      - UWU=build
    volumes:
      - ./cloud:/cloud
    ports:
      - 25567:25565
  survival:
    restart: always
    privileged: True
    build: minecraft
    tmpfs:
      - /tmp
    env_file: default.env
    depends_on:
      - db
    environment: 
      - UWU=survival
    volumes:
      - ./cloud:/cloud
    ports:
      - 25566:25565
  waterfall:
    build: waterfall
    ports: 
    - 25565:25565
volumes:
  cloud:
# networks: 
#   front:
#     driver: bridge
#   back: