listeners:
- query_port: 25565
  motd: Mine in Abyss
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    build.mineinabyss.com: build
    survive.mineinabyss.com: survival
    test.mineinabyss.com: test
  ping_passthrough: false
  priorities:
  - build
  - survival
  bind_local_address: true
  max_players: 40
  ab_size: 60
  force_default_server: false
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeeresourcepacks.command.usepack
  admin:
  - bungeeresourcepacks.command
  - bungeeresourcepacks.command.reload
  - bungeeresourcepacks.command.version
  - bungeeresourcepacks.command.generatehashes
  - bungeeresourcepacks.command.usepack.others
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - serverlistplus.admin
  - bungeetablistplus.command
  - bungeetablistplus.admin
log_pings: false
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: 35c8321c-ee11-47ed-8017-51dd6f15800b
player_limit: -1
ip_forward: true
groups:
  Derongan:
  - admin
  Offz:
  - admin
  Lizelive:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  build:
    motd: Mine In Abyss
    address: build:25566
    restricted: false
  survival:
    motd: Survive In Abyss
    address: hostip:25567
    restricted: false
  test:
    motd: Test In Abyss
    address: hostip:25568
    restricted: false
