# This is the main configuration file for Paper.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to Paper,
# join us in our Discord or IRC channel.
# 
# Discord: https://paperdiscord.emc.gs
# IRC: #paper @ irc.spi.gt ( http://irc.spi.gt/iris/?channels=paper )
# Website: https://papermc.io/ 
# Docs: https://paper.readthedocs.org/ 

verbose: false
config-version: 20
settings:
  enable-player-collisions: true
  player-auto-save-rate: -1
  max-player-auto-save-per-tick: -1
  use-alternative-luck-formula: false
  load-permissions-yml-before-plugins: true
  bungee-online-mode: true
  save-empty-scoreboard-teams: false
  incoming-packet-spam-threshold: 300
  sleep-between-chunk-saves: false
  region-file-cache-size: 256
  save-player-data: true
  use-versioned-world: false
  queue-light-updates-max-loss: 10
  suggest-player-names-when-null-tab-completions: true
  async-chunks:
    enable: true
    generation: true
    thread-per-world-generation: true
    load-threads: -1
  book-size:
    page-max: 2560
    total-multiplier: 0.98
  velocity-support:
    enabled: false
    online-mode: false
    secret: ''
  watchdog:
    early-warning-every: 5000
    early-warning-delay: 10000
  spam-limiter:
    tab-spam-increment: 1
    tab-spam-limit: 500
timings:
  server-name: Unknown Server
  enabled: true
  verbose: true
  server-name-privacy: false
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  history-interval: 300
  history-length: 3600
messages:
  no-permission: '&cI''m sorry, but you do not have permission to perform this command.
    Please contact the server administrators if you believe that this is in error.'
  kick:
    authentication-servers-down: ''
    connection-throttle: Connection throttled! Please wait before reconnecting.
    flying-player: Flying is not enabled on this server
    flying-vehicle: Flying is not enabled on this server
world-settings:
  default:
    iron-golems-can-spawn-in-air: false
    zombie-villager-infection-chance: -1.0
    seed-based-feature-search: true
    portal-create-radius: 16
    per-player-mob-spawns: false
    fix-zero-tick-instant-grow-farms: true
    entities-target-with-follow-range: false
    baby-zombie-movement-modifier: 0.5
    count-all-mobs-for-spawning: false
    nether-ceiling-void-damage-height: 0
    keep-spawn-loaded: true
    keep-spawn-loaded-range: 8
    auto-save-interval: -1
    disable-thunder: false
    skeleton-horse-thunder-spawn-chance: 0
    disable-ice-and-snow: false
    fire-physics-event-for-redstone: false
    skip-entity-ticking-in-chunks-scheduled-for-unload: true
    armor-stands-do-collision-entity-lookups: true
    nether-ceiling-void-damage: false
    allow-non-player-entities-on-scoreboards: false
    container-update-tick-rate: 1
    parrots-are-unaffected-by-player-movement: false
    grass-spread-tick-rate: 1
    water-over-lava-flow-speed: 5
    bed-search-radius: 1
    use-faster-eigencraft-redstone: true
    disable-explosion-knockback: false
    prevent-tnt-from-moving-in-water: false
    non-player-arrow-despawn-rate: -1
    creative-arrow-despawn-rate: -1
    armor-stands-tick: true
    spawner-nerfed-mobs-should-jump: false
    allow-leashing-undead-horse: false
    baby-zombie-movement-speed: 0.5
    all-chunks-are-slime-chunks: false
    mob-spawner-tick-rate: 1
    remove-corrupt-tile-entities: false
    fixed-chunk-inhabited-time: -1
    queue-light-updates: false
    disable-teleportation-suffocation-check: false
    portal-search-radius: 128
    optimize-explosions: false
    use-vanilla-world-scoreboard-name-coloring: false
    delay-chunk-unloads-by: 10s
    max-auto-save-chunks-per-tick: 6
    save-queue-limit-for-auto-save: 50
    enable-treasure-maps: true
    treasure-maps-return-already-discovered: false
    experience-merge-max-value: -1
    max-chunk-sends-per-tick: 81
    max-chunk-gens-per-tick: 10
    prevent-moving-into-unloaded-chunks: false
    falling-block-height-nerf: 0
    tnt-entity-height-nerf: 0
    filter-nbt-data-from-spawn-eggs-and-related: true
    max-entity-collisions: 8
    disable-creeper-lingering-effect: false
    duplicate-uuid-resolver: saferegen
    duplicate-uuid-saferegen-delete-range: 32
    anti-xray:
      enabled: false
      engine-mode: 1
      chunk-edge-mode: 2
      max-chunk-section-index: 3
      update-radius: 2
      hidden-blocks:
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - redstone_ore
      - lit_redstone_ore
      - clay
      - emerald_ore
      - ender_chest
      replacement-blocks:
      - stone
      - planks
    game-mechanics:
      nerf-pigmen-from-nether-portals: false
      disable-pillager-patrols: false
      disable-relative-projectile-velocity: false
      disable-end-credits: false
      disable-player-crits: false
      disable-sprint-interruption-on-attack: false
      disable-chest-cat-detection: false
      shield-blocking-delay: 5
      disable-unloaded-chunk-enderpearl-exploit: true
      scan-for-legacy-ender-dragon: true
      villages-load-chunks: false
    squid-spawn-height:
      maximum: 0.0
    max-growth-height:
      cactus: 3
      reeds: 3
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 600
    despawn-ranges:
      soft: 32
      hard: 128
    lightning-strike-distance-limit:
      sound: -1
      impact-sound: -1
      flash: -1
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
    lootables:
      auto-replenish: false
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
    hopper:
      cooldown-when-full: true
      disable-move-event: true
    alt-item-despawn-rate:
      enabled: false
      items:
        COBBLESTONE: 300
    generator-settings:
      flat-bedrock: false
