name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build minecraft image
      run: docker build --rm -t mineinabyss/minecraft:latest minecraft
    - name: Build waterfall image
      run: docker build --rm -t mineinabyss/waterfall:latest waterfall
